INTENTS = [
    {"tag": "greeting", "patterns": ["Hi", "Hello", "Hey"],
     "responses": ["Hi there", "Hello", "Hey"]},
    {"tag": "greeting", "patterns": ["How are you", "What's up"],
     "responses": ["I'm fine, thank you", "Nothing much"]},
    {"tag": "goodbye", "patterns": ["Bye", "See you later", "Goodbye", "Take care"],
     "responses": ["Goodbye", "See you later", "Take care"]},
    {"tag": "thanks", "patterns": ["Thank you", "Thanks", "Thanks a lot", "I appreciate it"],
     "responses": ["You're welcome", "No problem", "Glad I could help"]},
    {"tag": "joke", "patterns": ["Tell me a joke", "Make me laugh", "Funny joke"],
     "responses": ["Why don’t skeletons fight each other? Because they don’t have the guts!",
                   "Why was the math book sad? It had too many problems."]},
    {"tag": "fun_fact", "patterns": ["Tell me a fun fact", "Give me a fact", "Interesting fact"],
     "responses": ["Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3000 years old and still perfectly good to eat!"]},
    {"tag": "love", "patterns": ["i love you", "i love you chat bot", "i like you so much"],
     "responses": ["i love you too", "thanks honey", "i like you too"]},
    {"tag": "fallback", "patterns": [],
     "responses": ["I'm sorry, I didn't understand that. Could you rephrase?",
                   "Hmm, I’m not sure about that. Maybe try asking differently?"]},
]
